// Generated by CoffeeScript 1.4.0
(function() {
  var $, account_path, fs, messages;

  $ = jQuery;

  fs = require('fs');

  account_path = 'account.json';

  messages = $('#messages');

  $(document).ready(function() {
    return fs.exists(account_path, function(exists) {
      if (!exists) {
        console.log(messages);
        return messages.append($('<div class="alert alert-danger" role="alert">\
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>\
  <span class="sr-only">Error:</span>\
  No Accounts added. <a href="#"> Add account now?</a>\
</div>'));
      }
    });
  });

}).call(this);
